Hw1
dvan2/CS464-frontend-homework pull request #1
Opened 2023-10-04 20:01 UTC by dvan2

I've finished hw1 for the CSS game and the Palindrome program included in hw1.

The CSS game is pretty straight forward so I don't expect to have to change anything there. 

I'm mainly looking for feedback in 02-palindrome.js.  I tried to follow the Airbnb style guide as much as possible but I might miss a few.  Please feel free to leave a feedback if I miss any.

I'm aware that my algorithm for checking palindrome might be a little different.  I found that this worked just fine.  Feel free to test different inputs and see if you can break the algorithm.

2023-10-05 17:57 UTC, sieday requested changes
Hello! I just finished reviewing your Homework 1. Here is a quick summary of the comments that I added:

- There is no helpful error when the user inputs a negative value. The page states that the number is not a palindrome even though it cannot account for negative numbers.
- For AirBnb single quotes are preferred over double (6.1)
- For Airbnb === is preferred over == (15.1)
- For Airbnb x += 1 is preferred over ++ (13.6)

On a side note, your homework does not include any bootstrap classes or visual effects. I am not sure if this is an actual requirement. but it could be worth adding a CSS file or reclassing some of your items in the html file to use bootstrap's visual effects.

Let me know what you think and if you have any clarifying questions. Thank you!

P.S. I also thought it was neat that we used different selectors for some of the plate activities :)

2023-10-05 17:57 UTC, sieday commented on hw1/02-palindrome.js
> +  if (user_input == "") {
Best to use === over == (AirBnb - 15.1)

2023-10-05 17:57 UTC, sieday commented on hw1/02-palindrome.js
> +    if (s[first] != s[last]) {
Best to use !== over != (AirBnb - 15.1)

2023-10-05 17:57 UTC, sieday commented on hw1/02-palindrome.js
> +    if (s[first] != s[last]) {
Best to use !== over != (AirBnb - 15.1)

2023-10-05 17:57 UTC, sieday commented on hw1/02-palindrome.js
> +    resultElem.innerHTML = "ERROR.  Please enter only numbers.";
Best to use single quotes with strings (AirBnb - 6.1). I changed my settings in prettier so it did it for me which was super useful.

2023-10-05 17:57 UTC, sieday commented on hw1/02-palindrome.js
> +    resultElem.innerHTML = "Yes. This is a palindrome";
Best to use single quotes with strings (AirBnb - 6.1).

2023-10-05 17:57 UTC, sieday commented on hw1/02-palindrome.js
> +    resultElem.innerHTML = "Not palindrome. Try again.";
Best to use single quotes with strings (AirBnb - 6.1).

2023-10-05 17:57 UTC, sieday commented on hw1/02-palindrome.js
> +  if (elem.validity.badInput) {
Does not give a helpful error if the number is negative. Page states that all negative numbers are not palindromes rather than presenting an error.

2023-10-05 17:57 UTC, sieday commented on hw1/02-palindrome.js
> +    first++;
Best to use first += 1 rather than ++ (AirBnb 13.6).

2023-10-05 17:57 UTC, sieday commented on hw1/02-palindrome.js
> +    last--;
Best to use last -= 1 rather than -- (AirBnb 13.6).

2023-10-06 02:20 UTC, deanajackson commented
Hi David, that was a neat, and seamless solution that you used! I like how you used the isPalindrome() helper function. Your functions each have a unique purpose and that's a great practice. 
I did notice that there was no error message for negative numbers but how you did have an error for non numbers.
Finally, you didn't make use of Bootstrap which I think was supposed to help us review. 

I read Sienna's comment as well and realized I missed several styleguide points. Specifically: 
For Airbnb === is preferred over == (15.1)
For Airbnb x += 1 is preferred over ++ (13.6)
Thanks to Sienna for the sharp eye!

2023-10-06 02:22 UTC, deanajackson requested changes
Hi David, that was a neat, and seamless solution that you used! I like how you used the isPalindrome() helper function. Your functions each have a unique purpose and that's a great practice.
I did notice that there was no error message for negative numbers but how you did have an error for non numbers.
Finally, you didn't make use of Bootstrap which I think was supposed to help us review.

I read Sienna's comment as well and realized I missed several styleguide points. Specifically:
For Airbnb === is preferred over == (15.1)
For Airbnb x += 1 is preferred over ++ (13.6)
Thanks to Sienna for the sharp eye!

2023-10-11 18:38 UTC, closed without merging