Hw2
dvan2/CS464-frontend-homework pull request #2
Opened 2023-10-19 01:53 UTC by dvan2

Hello everyone.  I didn't expect this homework to take me this long.  Really sorry on my part.  I thought it might have been similar to the 1st HW.  I got started working on it on Monday and it wasn't enough really because I'm a novice programmer.

I barely finished all the stuff.  There is definitely a lot to improve and I'll keep working on it after this pull request.  I suspect there's a lot of things I might have missed just because there wasn't really any more time left.

I've learned my lesson and I will make sure to start out early next time.  Thanks everyone.

2023-10-20 14:50 UTC, deanajackson commented on hw2/03-count.js
> +  if (e.key !== "Backspace") {
If user presses w + shift, capslock etc(or any other non alpha charatter) that gets added to the user input, like backspace would. So w+shift + a + s will not highlight was. This was a tricky part of this ex that I also didn't have a leak proof implementation for. Only adding key values to the string that can be seen in the field or expected to be searched for.

2023-10-20 14:50 UTC, deanajackson commented on hw2/03-count.js
> +  console.log(user_input);
I know we are supposed to remove extra code but I think these console.log() are really helpful for us reviewers :)

2023-10-20 14:50 UTC, deanajackson commented on hw2/03-count.js
> +let textString = text.textContent;
I didn't know about this Dom element .textContent. I like it!

2023-10-20 14:50 UTC, deanajackson commented on hw2/03-count.js
> +    (match) => `<span class="bg-warning">${match}</span>`
Nice use of bg-warning!

2023-10-20 14:50 UTC, deanajackson commented on hw2/03-count.html
> +  <body class="bg-secondary">
Nice job using bootstrap this time! The website is a little hard to track stuff down in but once you find what you need it's pretty good!

2023-10-20 14:50 UTC, deanajackson commented on hw2/03-count.html
> +        <input type="text" />
Label needs to have for="" and input needs the id and name and be part of a form group

2023-10-20 14:50 UTC, deanajackson commented on hw2/04-background.html
>          <label>Background change interval (seconds): </label>
Also needs the for="" attribute. I usually forget this but from Caterina's intro class I remember to use WAVE: https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh If you dont already have it :)

2023-10-20 14:50 UTC, deanajackson commented on hw2/04-background.html
> +        <input type="number" class="form-control" style="width: 50%" />
A good opportunity to have a default value of 3. value="3" then the JS can pull the initial value and start changing the background on load, then respond to user changes as needed

2023-10-20 14:50 UTC, deanajackson commented on hw2/04-background.js
> +  if (user_input <= 0) {
You can also specify min and max values as attributes on the input tag element min = 1 max = 100 for example

2023-10-20 14:50 UTC, deanajackson commented on hw2/04-background.js
> +  if (user_input <= 0) {
But I like that it gives the user a warning telling them what they cannot do! with min and max they might wonder why the arrows "aren't doing what they are supposed to"

2023-10-20 14:50 UTC, deanajackson commented on hw2/04-background.js
> +    clearInterval(nIntervId);
Good job with remembering clearInterval(). I was stuggling to update my intervals until I read closer and found this

2023-10-20 14:50 UTC, deanajackson commented on hw2/04-background.js
> +}
nice

2023-10-20 14:50 UTC, deanajackson commented on hw2/05-form.js
> +  if (!pLanguages && !oSystems && !fullStack) {
nice, I like how you are taking care of different cases

2023-10-20 14:50 UTC, deanajackson commented on hw2/05-form.js
> +  const message = document.querySelector("textarea").value;
Nice job using const for all of these

2023-10-20 23:22 UTC, sieday requested changes
Looks good! 

Added a few style notes. Only things are that your count functionality highlights subsections of words rather than just whole words - example in second screenshot in homework document and your background functionality does not start by going every 3 seconds. Great job accounting for lots of input cases!

2023-10-20 23:22 UTC, sieday commented on hw2/03-count.js
Highlights sections within words instead of only entire words - example in second screenshot of homework pdf.

2023-10-20 23:22 UTC, sieday commented on hw2/04-background.html
Does not start with 3 second interval background change

2023-10-22 06:50 UTC, dvan2 commented on hw2/03-count.js
> +  if (e.key !== "Backspace") {
I was able to fix this by using this source: https://stackoverflow.com/questions/12467240/determine-if-javascript-e-keycode-is-a-printable-non-control-character

2023-10-23 22:43 UTC, merged